### ISSUE TITLE
ability to update domain and subdomains 

### ISSUE THREAD

**Issue by kamilmirza** [TimothyYe/godns#76]
same issue as in #33 
where you replied on adding the ability to update domain and subdomain, altogether 

> Good suggestion!  I'll consider to add it, thanks!

_Originally posted by @TimothyYe in https://github.com/TimothyYe/godns/issues/33#issuecomment-457039340_

later issue #33 got offtrack and closed

is there any chance to have this ability on future releases?

here's my config:
```  "domains": [{
      "domain_name": "example.com"
    },{
      "domain_name": "example.com",
      "sub_domains": ["*"]
    }
  ],

**Comment by jlsalvador** [comment]
- [ ] alidns
- [X] cloudflare
- [ ] dnspod
- [ ] dreamhost
- [ ] duck
- [ ] google
- [ ] he
- [ ] noip

cdf32c509d4bd6c1a033632feb2f36c16ae1e3cd

**Comment by iskrisis** [comment]
I would've never thought this isn't supported... is there a reason why? It's like the main reason for software like this no? And from the PR it seems its basically no change?!?

**Comment by jlsalvador** [comment]
Hello @iskrisis . I think this issue is about the typical free-time and resource starvation that every open source project have.

Yes, it's true that the implementation that fix this issue for Cloudflare seemed really easy, but that doesn't mean the same solution applies to the other services. The easy-path solution for Cloudflare was that the API is the same for domains and subdomains, so I only needed to return the domain as a subdomain in order to fix this issue. I don't have the need and the resources (because I just use Cloudflare as my DNS Domain provider) to investigate and fix this issue for the other services.

And here comes the magic of the open-source. Someone with the tech-skills, needs, and resources could come here with a PR to fix the other services. Meanwhile, you can incentive this kind of uninterested behavior with a good-looking, maintained, and healthy project. I came here with this PR because I had the need to have a DDNS in my router (GoLang is a good portable language), the code was easy to understand, and it supports Cloudflare. When I saw that my requirements was easy to fix with just a few lines, I sent the patch. Help us to maintain a good looking project (better codes/docs, with community, etc) and eventually someone with the same requirements will send us a PR for the other services.

Even I'll encore you to try to send any PR that could help this project healthy. GoLang is an easy language to start programming. Grab any issue or start working on anything that you think can help this project to be attractive to more persons. :-)

**Comment by iskrisis** [comment]
@jlsalvador please don't take this the wrong way. I understand the burden of OSS and i am fully aware that i can make PRs. I also maintain some stuff.

But i think there is also other side of the coin and thats if you are making DDNS client and you for some reason don't support updating of root records which is definition of CORE feature... It seems like very artificial limitation considering software is already able to do it.

Maybe just don't pose as super nice software with LOGO and documentation.. support tables.. Mention that it's not supporting root records in those docs. The project looked like the most legit of the ones i found. It took me quite some time to figure out that it won't update root records. I thought i must have made configuration error.

Maybe you are without reason wasting time of someone who can't help you with Go and can't even build the project and uses the release binary. This happens when you offer the software to the world. Yes lame people use it. And yes you have all the rights but there is also something about being precious about your users.

**Comment by TimothyYe** [comment]
@iskrisis Calm down bro, the original reason was, when the first time I design this tool, I only had one domain. I use root record to host my personal blog and use sub-domain for DDNS purposes. If one domain can be used for multiple purposes, then it looks good to me. For my personal scenario, I don't have the need to update the root record for DDNS. Sorry for the time you wasted, if you think updating root records is definitely a CORE feature, I will add it.

@jlsalvador Thanks for your patient and explanation, and thanks for the PR again.

**Comment by iskrisis** [comment]
@TimothyYe  i don't want you to add anything. I was just asking for more clear description. Something like this https://github.com/TimothyYe/godns/pull/99 There are many DDNS projects. Yours just looks the best and the most complete (you even mention its rewrite of different projects so it looks double legit) so one would expect its super feature packed and complete.

Just saying guys

**Comment by TimothyYe** [comment]
Close this issue since it is already supported by V2.3.4 (https://github.com/TimothyYe/godns/releases/tag/V2.3.4)
